"""initial schema

Revision ID: 415a6a7537e2
Revises: 
Create Date: 2026-07-10 12:28:56.981543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '415a6a7537e2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health_workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('nurse', 'facility_admin', 'system_admin', name='workerrole'), nullable=False),
    sa.Column('preferred_language', sa.Enum('en', 'rw', name='language'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_id'], ['health_workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('health_worker_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['health_worker_id'], ['health_workers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='gender'), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('condition', sa.Enum('hypertension', 'type2_diabetes', 'hiv', name='condition'), nullable=False),
    sa.Column('language', sa.Enum('en', 'rw', name='language'), nullable=False),
    sa.Column('status', sa.Enum('active', 'deactivated', name='patientstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['health_workers.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adherence_checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('sent_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('sent', 'confirmed', 'not_confirmed', 'no_response', name='checkinstatus'), nullable=False),
    sa.Column('response', sa.Enum('yes', 'no', name='checkinresponse'), nullable=True),
    sa.Column('response_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_missed', sa.Integer(), nullable=False),
    sa.Column('worker_notified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recurrence_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('upcoming', 'attended', 'missed', 'followed_up', name='appointmentstatus'), nullable=False),
    sa.Column('attended_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('follow_up_note', sa.Text(), nullable=True),
    sa.Column('reminder_48h_sent', sa.Boolean(), nullable=False),
    sa.Column('reminder_24h_sent', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointments')
    op.drop_table('adherence_checkins')
    op.drop_table('patients')
    op.drop_table('password_reset_tokens')
    op.drop_table('audit_logs')
    op.drop_table('health_workers')
    op.drop_table('facilities')
    # ### end Alembic commands ###
